{
 "title": "Docker Desktop",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\",instance=\"docker-desktop\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"docker-desktop\"} - node_memory_MemFree_bytes{instance=\"docker-desktop\"} - node_memory_Buffers_bytes{instance=\"docker-desktop\"} - node_memory_Cached_bytes{instance=\"docker-desktop\"}) \r\n/ node_memory_MemTotal_bytes{instance=\"docker-desktop\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ( sum by (instance) (node_filesystem_free_bytes{instance=\"docker-desktop\"}) / sum by (instance) (node_filesystem_size_bytes{instance=\"docker-desktop\"})* 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}