{
 "title": "Java-service",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Сервис",
    "query": "payment-service,balance-service, notification-service"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"java-services\", service=~\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_usage{service=~\"$service\"} * 100 ",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage JVM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{service=~\"$service\", area=\"heap\"}) by (service)/sum(jvm_memory_max_bytes{service=~\"$service\", area=\"heap\"}) by (service))* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(service) (increase(http_server_requests_seconds_count{service=~\"$service\"}[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}