{
 "title": "Kafka",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Kafka Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Partitions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partitions{instance=\"kafka-broker:9308\", job=\"kafka\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (topic,consumergroup) (kafka_consumergroup_lag{instance=\"kafka-broker:9308\", job=\"kafka\"})",
     "legendFormat": "{{topic}} - {{consumergroup}}"
    }
   ]
  },
  {
   "title": "Message Consumption Rate",
   "type": "timeseries",
   "description": "скорость потребления сообщений",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_topic_partition_current_offset{instance=\"kafka-broker:9308\", job=\"kafka\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}