{
 "title": "Postgres and Redis",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "db_name",
    "label": "База данных",
    "query": "payment-db,balance-db, notification-db"
   }
  ]
 },
 "panels": [
  {
   "title": "Status Database",
   "type": "stat",
   "description": "Статус Базы данных",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_up{db_name=~\"$db_name\"}",
     "legendFormat": "{{db_name}}"
    }
   ]
  },
  {
   "title": "Redis status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_up{job=\"redis\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Size DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": " sum by (db_name) (pg_database_size_bytes{db_name=~\"$db_name\"})   ",
     "legendFormat": "{{db_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage Redis (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{job=\"redis\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Operations/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_ins{db_name=~\"$db_name\",relname!=\"flyway_schema_history\"}[5m]) + \r\nrate(pg_stat_user_tables_n_tup_upd{db_name=~\"$db_name\",relname!=\"flyway_schema_history\"}[5m]) + \r\nrate(pg_stat_user_tables_n_tup_del{db_name=~\"$db_name\",relname!=\"flyway_schema_history\"}[5m]) ",
     "legendFormat": "{{db_name}} ({{relname}})"
    }
   ]
  },
  {
   "title": "Commands/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{job=\"redis\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{db_name=~\"$db_name\",application_name=\"PostgreSQL JDBC Driver\"}",
     "legendFormat": "{{db_name}}"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "redis_connected_clients{job=\"redis\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}