{
 "title": "Микросервисы - общий мониторинг",
 "description": "Общий мониторинг ",
 "time": { "from": "2025-11-21T03:22:53.686Z", "to": "2025-11-21T04:22:53.686Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Сервис",
    "query": "payment-service,balance-service, notification-service"
   },
   { "name": "http_status_filter", "label": "HTTP статусы", "query": "'2..',3..,4..,5.." }
  ]
 },
 "panels": [
  {
   "title": "Статус сервиса",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$service\"}",
     "legendFormat": "{{job}} - {{value}}"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "description": "Загрузка процессора по сервисам",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=~\"$service\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Memory Usage JVM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{job=~\"$service\", area=\"heap\"}) by (job)/sum(jvm_memory_max_bytes{job=~\"$service\", area=\"heap\"}) by (job))* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=~\"$service\", status=~\".*\"}[5m]) ",
     "legendFormat": "{{job}}:{{status}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Kafka Status",
   "type": "timeseries",
   "description": "Consumer lag, throughput and errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lag{job=~\"$service\"}",
     "legendFormat": "{{job}} - {{topic}} - Lag"
    },
    {
     "expr": "rate(kafka_consumer_messages_processed_total{job=~\"$service\"}[5m])",
     "legendFormat": "{{job}} - {{topic}} - Msg/sec"
    },
    {
     "expr": "rate(kafka_consumer_errors_total{job=~\"$service\"}[5m])",
     "legendFormat": "{{job}} - {{topic}} - Errors/sec"
    }
   ]
  }
 ]
}